const Router = require('@koa/router');
const contract = require('./routes/contract');
const status = require('./routes/status');
const contractViewState = require('./routes/contractViewState');
const contractQueryState = require('./routes/contractQueryState');
const blacklisted = require('./routes/blacklisted');
const cached = require('./routes/cached');
const errors = require('./routes/errors');
const scheduleSync = require('./routes/scheduleSync');
const kv = require('./routes/kv');
const eraseContract = require('./routes/eraseContract');
const validity = require('./routes/validity');
const { walletBalances } = require('./routes/agg/aggBalances');
const { interactions } = require('./routes/agg/aggInteractionsByIndex');
const { taggedNftByOwner } = require('./routes/agg/aggTaggedNftByOwner');
const alive = require('./routes/alive');
const syncLog = require('./routes/syncLog');
const { warpyUserLastRewards } = require('./routes/warpy/warpyUserLastRewards');
const { warpySeasonRanking } = require('./routes/warpy/warpySeasonRanking');
const { warpyUserId } = require('./routes/warpy/warpyUserId');
const { warpyUserBalance } = require('./routes/warpy/warpyUserBalance');
const { warpyUserCounter } = require('./routes/warpy/warpyUserCounter');
const { warpyUserRanking } = require('./routes/warpy/warpyUserRanking');

const router = new Router();

router.get('/balances', walletBalances);
router.get('/interactions-by-indexes', interactions);
router.get('/nft-by-owner', taggedNftByOwner);
router.get('/contract', contract);
router.get('/alive', alive);
router.get('/contract/view-state', contractViewState);
router.get('/status', status);
router.get('/blacklist', blacklisted);
router.get('/cached', cached);
router.get('/errors', errors);
router.get('/sync', scheduleSync);
router.get('/kv', kv);
router.get('/validity', validity);
router.get('/sync-log', syncLog);
router.get('/pg/contract', contractQueryState);
router.get('/warpy/user-last-rewards', warpyUserLastRewards);
router.get('/warpy/season-ranking', warpySeasonRanking);
router.get('/warpy/user-id', warpyUserId);
router.get('/warpy/user-balance', warpyUserBalance);
router.get('/warpy/user-counter', warpyUserCounter);
router.get('/warpy/user-ranking', warpyUserRanking);
router.delete('/contract/:id', eraseContract);

module.exports = router;
